on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        cd build_and_deploy && \
        npm install .

    - name: Convert Node.js code to binary
      run: pkg -t node14-linux-x64 main.js -o synapse-deploy

    - name: Get commit SHA suffix
      id: get_commit_sha_suffix
      run: |
        echo "::set-output name=commit_sha_suffix::$(echo ${GITHUB_SHA: -5})"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          synapse-deploy
        tag_name: 1.0-${{ steps.get_commit_sha_suffix.outputs.commit_sha_suffix }}
        body: 'new body text'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
